### ISSUE TITLE
Package Name Scope Recommendation

### ISSUE THREAD

**Issue by lsw1164** [AppsFlyerSDK/appsflyer-unity-adrevenue-generic-connector#13]
Unity recommends the following naming convention for package names: com.{companyname}.{name}. 
Reference: [Unity Manual: Package naming](https://docs.unity3d.com/Manual/cus-naming.html).

Currently, each package provided by Appsflyer has a separate scope, which complicates management, especially when adding new packages, as a new scope needs to be added each time.

Recommendation:
To streamline the process and enhance manageability, I recommend the following package names:

- For the core Unity plugin: 
appsflyer-unity-plugin -> `com.appsflyer.core`

- For the ad revenue generic connector: 
appsflyer-unity-adrevenue-generic-connector -> `com.appsflyer.adrevenue-generic-connector`

This approach allows all packages under the com.appsflyer scope to be easily identified as provided by Appsflyer.

Benefits:
Simplified package management
Consistent naming convention in line with Unity recommendations
Easier identification of Appsflyer packages within the com.appsflyer scope

Thanks.

**Comment by af-vero** [comment]
Hi @lsw1164,
Thanks for your comment, noted
