### ISSUE TITLE
Missing version ad revenue connector 6.14.4 which is dependent on the latest AppsFlyer sdk 6.14.4

### ISSUE THREAD

**Issue by silviosav-SEGA-HARDlight** [AppsFlyerSDK/appsflyer-unity-adrevenue-generic-connector#14]
Hello,

At the moment we can't use the latest AppsFlyer Unity plugin sdk 6.14.4 because the ad revenue connect Unity plugin 16.4.3 has a podspec on iOS requiring the sdk 6.14.3 instead.

```
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "AppsFlyerFramework":
  In Podfile:
    AppsFlyer-AdRevenue (= 6.14.3) was resolved to 6.14.3, which depends on
      AppsFlyerFramework (= 6.14.3)

    AppsFlyerFramework (= 6.14.4)
```

Please could you do a new ad revenue connect Unity plugin to fix this up?

Thanks,
Silvio

**Comment by af-vero** [comment]
👋 Hi @silviosav-SEGA-HARDlight  and Thank you for reaching out to us.
In order for us to provide optimal support, please submit a ticket to our support team at [support@appsflyer.com](mailto:support@appsflyer.com).
When submitting the ticket, please specify:

✅ your AppsFlyer sign-up (account) email
✅ app ID
✅ production steps
✅ logs
✅ code snippets
✅ and any additional relevant information.

**Comment by silviosav-SEGA-HARDlight** [comment]
Hi, @af-vero I'll do but what's the point of having the Issues tab open publicly if you redirect me to a support email?

**Comment by af-vero** [comment]
Hi, 
There are issues that we can handle here, but there are some issues that can be prioritized only through support/product.

**Comment by silviosav-SEGA-HARDlight** [comment]
Hi,

thanks, you can close it up, I was told from the support ticket that they won't be making a new release or use a pessimistic operator in the podspec dependency because they're working to include the ad revenue connector API into the sdk itself.

I can easily downgrade and use the 6.14.3 because I don't need the changes in the update of sdk 6.14.4. Unfortunately anyone needing that and also the ad revenue connector will need to wait for a future release.
