### ISSUE TITLE
UPM, iOS: AppsFlyerAdRevenue.cs(60,93): error CS0103: The name 'AFMiniJSON' does not exist in the current context

### ISSUE THREAD

**Issue by Weiky23** [AppsFlyerSDK/appsflyer-unity-adrevenue-generic-connector#5]
Hello.
Installing both the main AppsFlyer SDK and AdRevenue through UPM results in error when attempting to build for iOS.
```
AppsFlyerAdRevenue.cs(60,93): error CS0103: The name 'AFMiniJSON' does not exist in the current context
``` 
It appears that there may be a need to reference the main SDK assembly.
![image](https://github.com/AppsFlyerSDK/appsflyer-unity-adrevenue-generic-connector/assets/11775256/95db1925-f889-4c03-a5ac-0f95bc02b9e1)

**Comment by af-do** [comment]
Hi @Weiky23 @RussellPN,
Thank you for raising this issue, this is fixed in the latest versions of our AF Unity Plugin (v6.12.22) and AF Unity Generic AdRev Connector (v6.9.41), updating should resolve this error.
