### ISSUE TITLE
UPM, iOS: Undefined Symbols failing xCode build

### ISSUE THREAD

**Issue by ChristianMcFarlaneWork** [AppsFlyerSDK/appsflyer-unity-adrevenue-generic-connector#7]
Hey,
We've added this plugin, and while the build works fine on Android, when building for iOS we get this error during the xCode build.
```C
ld: Undefined symbols:
  stringFromChar(char const*), referenced from:
      __logAdRevenue in AppsFlyerAdRevenueWrapper.o
      __logAdRevenue in AppsFlyerAdRevenueWrapper.o
  dictionaryFromJson(char const*), referenced from:
      __logAdRevenue in AppsFlyerAdRevenueWrapper.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Using:
- Unity 2021.3.21f1
- AppsFlyer SDK 6.12.22 - via UPM
- AppsFlyer AdRevenue Connector 6.9.41 - via UPM
- Mac Mini M2 on MacOS Sonoma 14.1.1
- Xcode 15.0.1 (15A507)

Cheers in advance. Let us know if there's anything more I can provide.

**Comment by af-do** [comment]
Hi @ChristianMcFarlaneWork,
Thank you for reaching out to us.
Indeed there is an issue with version 6.9.41, we released a fix for this in version 6.9.42 - updating should resolve this issue once and for all.
