### ISSUE TITLE
Where is the Apple Privacy Manifest update?

### ISSUE THREAD

**Issue by NvHulst** [AppsFlyerSDK/appsflyer-unity-adrevenue-generic-connector#9]
Regarding Apple's privacy manifest, I was wondering when the update for this package will come?
Tomorrow it's May 1st which is basically the deadline, however I don't see any update yet.

Source: [https://developer.apple.com/support/third-party-SDK-requirements/](https://developer.apple.com/support/third-party-SDK-requirements/)

**Comment by NvHulst** [comment]
May 1st has passed, I wonder when there will be an update.
If it's not needed, at least let me know if the core package is sufficient.

**Comment by af-vero** [comment]
Hi, we have privacy manifest as part of our Unity plugin. Regarding the adrevenue connector, we don't need to declare anything for now.
Thanks

**Comment by NvHulst** [comment]
Thanks for the answer!

**Comment by NvHulst** [comment]
Thanks for the answer!
